version: "3.2"

# services:
# sql-server-db:
#   container_name: sql-server-db
#   image: mcr.microsoft.com/mssql/server:2017-latest
#   ports:
#     - "1433:1433"
#   hostname: "sql-server-db"

#   environment:
#     MSSQL_SA_PASSWORD: "1234@Pass"
#     ACCEPT_EULA: "Y"
#   restart: on-failure

services:
  sql-server-db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sql-server-db
    user: root
    hostname: "sql-server-db"
    environment:
      MSSQL_SA_PASSWORD: "1234@Pass"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ~/docker/sql/mssql/:/var/opt/mssql/
      - ~/docker/sql/sqlserver/:/var/opt/sqlserver/
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "1234@Pass" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
